import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { getUser } from "@/lib/auth";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({ children }: { children: React.ReactNode }) {
  const user = await getUser();

  return (
    <html lang="en">
      <body>
        {/* Example: simple server-rendered nav without any client context */}
        <header className="border-b p-4">
          <div className="flex items-center justify-between">
            <span className="font-semibold">Census</span>
            <span className="text-sm text-gray-600">
              {user ? `Hi, ${user.username}` : "Not signed in"}
            </span>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
